apiVersion: apps/v1
kind: Deployment 
metadata:
  name: flaskapp
  namespace: flaskapp
  labels:
    app: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:  
    metadata:
      labels: 
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: 331523302307.dkr.ecr.ap-south-1.amazonaws.com/flaskapp:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "eks-database.cvy0kesckkwc.ap-south-1.rds.amazonaws.com"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "mydb"            
            - name: DB_USERNAME
              value: "admin"   
            - name: DB_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
