apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  namespace: flaskapp
  labels: 
    app: flaskapp
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
    - name: http
      port: 80
      targetPort: 5000
    - name: https
      port: 443   
      targetPort: 5000
